<script lang="ts" setup>
import { ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import StandardNotification from '@/components/standards/StandardNotification.vue'
import { useGroupsStore, type CreateGroup } from '@/stores/GroupsStore'

const router = useRouter()
const loading = ref(false)
const error = ref('')
const showNotification = ref(false)
const notificationMessage = ref('')
const notificationType = ref('success')

const groupsStore = useGroupsStore()

const group = ref<CreateGroup>({
  name: '',
  total_amount: 0,
  member_count: 1,
  start_date: '',
  end_date: '',
  status: 'active',
  number_of_months: 0,
  commission_percentage: 4,
  is_ten_dates_chit: false
})

// Function to calculate months or periods between two dates
function calculatePeriods(startDate: string, endDate: string, isTenDatesChit: boolean = false): number {
  if (!startDate || !endDate) return 0

  if (isTenDatesChit) {
    // Calculate number of 10-date periods (3 per month: 10th, 20th, 30th) - using string approach
    let count = 0
    const startParts = startDate.split('-');
    const endParts = endDate.split('-');
    
    let startYear = parseInt(startParts[0]);
    let startMonth = parseInt(startParts[1]);
    let endYear = parseInt(endParts[0]);
    let endMonth = parseInt(endParts[1]);
    
    // Generate dates from start month/year to end month/year
    for (let year = startYear; year <= endYear; year++) {
      let monthStart = (year === startYear) ? startMonth : 1;
      let monthEnd = (year === endYear) ? endMonth : 12;
      
      for (let month = monthStart; month <= monthEnd; month++) {
        // Count 10th, 20th, 30th of each month
        [10, 20, 30].forEach(day => {
          const monthStr = month.toString().padStart(2, '0');
          const dayStr = day.toString().padStart(2, '0');
          const dateString = `${year}-${monthStr}-${dayStr}`;
          
          // Skip February 30th manually
          if (month === 2 && day === 30) return;
          
          // Check if within range by string comparison
          if (dateString >= startDate && dateString <= endDate) {
            count++;
          }
        });
      }
    }
    
    return count
  } else {
    // Calculate months
    const start = new Date(startDate)
    const end = new Date(endDate)
    let months = (end.getFullYear() - start.getFullYear()) * 12 +
                 (end.getMonth() - start.getMonth())

    // If end day is after or equal to start day, count as full month
    if (end.getDate() >= start.getDate()) {
      months += 1
    }

    return Math.max(0, months)
  }
}

// Watch for changes in start_date, end_date, and is_ten_dates_chit
watch(
  [() => group.value.start_date, () => group.value.end_date, () => group.value.is_ten_dates_chit],
  ([newStartDate, newEndDate, isTenDatesChit]) => {
    group.value.number_of_months = calculatePeriods(newStartDate, newEndDate, isTenDatesChit)
  }
)

async function handleSubmit() {
  try {
    loading.value = true
    error.value = ''
    // Validate required fields and valid dates
    const start = group.value.start_date && !isNaN(Date.parse(group.value.start_date)) ? group.value.start_date.trim() : ''
    const end = group.value.end_date && !isNaN(Date.parse(group.value.end_date)) ? group.value.end_date.trim() : ''
    if (!start || !end) {
      error.value = 'Start Date and End Date are required and must be valid.'
      notificationMessage.value = error.value
      notificationType.value = 'error'
      showNotification.value = true
      loading.value = false
      return
    }
    // Ensure number_of_months is up-to-date before submit
    group.value.start_date = start
    group.value.end_date = end
    group.value.number_of_months = Number(calculatePeriods(start, end, group.value.is_ten_dates_chit))
    const createdGroup = await groupsStore.createGroup({
      ...group.value,
      number_of_months: Number(group.value.number_of_months)
    })
    
    // Note: Initial chit dates are now automatically generated by the backend
    
    notificationMessage.value = 'Group created successfully!'
    notificationType.value = 'success'
    showNotification.value = true
    setTimeout(() => {
      router.push('/groups')
    }, 1500)
  } catch (err: any) {
    console.error('Error creating group:', err)
    error.value = err.response?.data?.message || 'Failed to create group. Please try again.'
    notificationMessage.value = error.value
    notificationType.value = 'error'
    showNotification.value = true
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="add-group">
    <div class="header">
      <h2>Create New Chit Group</h2>
    </div>

    <form @submit.prevent="handleSubmit" class="group-form">
      <div v-if="error" class="error-message">
        {{ error }}
      </div>

      <div class="form-group">
        <label for="name">Group Name</label>
        <input
          type="text"
          id="name"
          v-model="group.name"
          required
          placeholder="Enter group name"
        />
      </div>

      <div class="form-group">
        <div class="checkbox-group">
          <input
            type="checkbox"
            id="is_ten_dates_chit"
            v-model="group.is_ten_dates_chit"
            class="checkbox-input"
          />
          <label for="is_ten_dates_chit" class="checkbox-label">
            Ten Dates Chit (10th, 20th, 30th of each month instead of monthly)
          </label>
        </div>
      </div>

      <div class="form-group">
        <label for="total_amount">Total Amount (₹)</label>
        <input
          type="number"
          id="total_amount"
          v-model="group.total_amount"
          required
          placeholder="Enter total amount"
          min="0"
        />
      </div>

      <div class="form-group">
        <label for="member_count">Number of Members</label>
        <input
          type="number"
          id="member_count"
          v-model="group.member_count"
          required
          placeholder="Enter number of members"
          min="1"
        />
      </div>

      <div class="form-group">
        <label for="start_date">Start Date</label>
        <input
          type="date"
          id="start_date"
          v-model="group.start_date"
          required
        />
      </div>

      <div class="form-group">
        <label for="end_date">End Date</label>
        <input
          type="date"
          id="end_date"
          v-model="group.end_date"
          required
        />
      </div>

      <div class="form-group">
        <label for="number_of_months">{{ group.is_ten_dates_chit ? 'Number of Periods (10-day intervals)' : 'Number of Months' }}</label>
        <input
          type="number"
          id="number_of_months"
          v-model="group.number_of_months"
          readonly
          class="readonly-input"
        />
        <small class="helper-text">{{ group.is_ten_dates_chit ? 'Automatically calculated based on start and end dates (10th, 20th, 30th of each month)' : 'Automatically calculated based on start and end dates' }}</small>
      </div>

      <div class="form-group">
        <label for="status">Status</label>
        <select id="status" v-model="group.status" required disabled class="readonly-input">
          <option value="active">Active</option>
        </select>
        <small class="helper-text">New groups are created as Active by default</small>
      </div>

      <div class="form-actions">
        <button type="submit" class="submit-button" :disabled="loading">
          {{ loading ? 'Creating...' : 'Create Group' }}
        </button>
        <button type="button" class="cancel-button" @click="router.push('/groups')" :disabled="loading">
          Cancel
        </button>
      </div>
    </form>


    <StandardNotification
      :message="notificationMessage"
      :type="notificationType"
      :show="showNotification"
      :duration="3000"
      @close="showNotification = false"
    />
  </div>
</template>

<style scoped>
.add-group {
  padding: 2rem;
  max-width: 600px;
  margin: 0 auto;
}

.header {
  margin-bottom: 2rem;
}

h2 {
  margin: 0;
  color: #2c3e50;
}

.group-form {
  background: white;
  padding: 2rem;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0,0,0,0.1);
}

.form-group {
  margin-bottom: 1.5rem;
}

label {
  display: block;
  margin-bottom: 0.5rem;
  color: #2c3e50;
  font-weight: 500;
}

input, select {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 4px;
  font-size: 1rem;
}

input:focus, select:focus {
  outline: none;
  border-color: #3498db;
}

.error-message {
  background-color: #fee2e2;
  color: #dc2626;
  padding: 0.75rem;
  border-radius: 4px;
  margin-bottom: 1.5rem;
  font-size: 0.875rem;
}

.form-actions {
  display: flex;
  gap: 1rem;
  margin-top: 2rem;
}

.submit-button, .cancel-button {
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  font-size: 1rem;
  transition: background-color 0.2s;
}

.submit-button {
  background-color: #2c3e50;
  color: white;
}

.submit-button:hover:not(:disabled) {
  background-color: #34495e;
}

.cancel-button {
  background-color: #95a5a6;
  color: white;
}

.cancel-button:hover:not(:disabled) {
  background-color: #7f8c8d;
}

button:disabled {
  opacity: 0.7;
  cursor: not-allowed;
}

.checkbox-group {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.checkbox-input {
  width: auto;
  margin: 0;
}

.checkbox-label {
  margin: 0;
  font-weight: normal;
  cursor: pointer;
}

.readonly-input {
  background-color: #f8f9fa;
  cursor: not-allowed;
}

.helper-text {
  color: #6c757d;
  font-size: 0.875rem;
  margin-top: 0.25rem;
  display: block;
}
</style>